stages:
  - build

build-job:
  stage: build
  image: eclipse-temurin:21-jdk

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

  script:
    - chmod +x mvnw
    - ./mvnw clean package

  artifacts:
    paths:
      - target/*.jar