stages:
  - build
  - test

build:
  stage: build
  image: eclipse-temurin:21-jdk
  tags:
    - saas-linux-small-amd64
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

sca:
  stage: test
  image: eclipse-temurin:21-jdk
  tags:
    - saas-linux-small-amd64
  script:
    - chmod +x mvnw
    - ./mvnw org.owasp:dependency-check-maven:check -Dformat=HTML -DautoUpdate=false
  artifacts:
    when: always
    paths:
      - target/dependency-check-report.*