name: CI + SAST + SCA

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:21-jdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build project
        run: ./mvnw clean package -DskipTests

      - name: SAST step
        run: echo "SAST already configured in previous practice"

      - name: Run SCA analysis (OWASP Dependency-Check)
        run: ./mvnw org.owasp:dependency-check-maven:check -Dformat=HTML -DautoUpdate=false

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sca-report
          path: target/dependency-check-report.*

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jar-file
          path: target/*.jar