name: Сборка проекта

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:21-jdk

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка прав mvnw
        run: chmod +x mvnw

      - name: Сборка проекта
        run: ./mvnw clean package -DskipTests

      - name: SCA Dependency Check
        run: ./mvnw org.owasp:dependency-check-maven:check -Dformat=HTML -DautoUpdate=false

      - name: Сохранение JAR артефакта
        uses: actions/upload-artifact@v4
        with:
          name: jar-файл
          path: target/*.jar

      - name: Сохранение SCA отчёта
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: target/dependency-check-report.*